version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tradingbotdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - trading-net

  python-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    tty: true
    depends_on:
      - postgres-db
    networks:
      - trading-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@joaquinsoza.dev
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - trading-net
  # Add other services like frontend here

networks:
  trading-net:

volumes:
  postgres-data:
